### ISSUE TITLE
Difference between "manifest" and "distributed derivation"

### ISSUE THREAD

**Issue by CMCDragonkai** [svanderburg/disnix#1]
I'm looking at the 2 commands:

`disnix-instantiate`

`disnix-manifest`

What's the difference between the output of these 2 commands.

**Comment by svanderburg** [comment]
disnix-manifest produces a low-level XML configuration file that is used for the following deployment activities: distributing, locking, activating, snapshotting and restoring services.

disnix-instantiate produces a low-level XML configuration file that is used for building the services on the target machines. It's (sort of) the distributed equivalent of a Nix store derivation file (*.drv) file. The building on target machines feature is optional. By default, builds are done on the coordinator machine.
