### ISSUE TITLE
Disnix manual not found

### ISSUE THREAD

**Issue by husnoo** [svanderburg/disnix#10]
404 Not Found
File /nix/store/jxq2xklvry5nlgzaf0swhrydcchviq80-disnix-tarball-0.7/share/doc/disnix/manual has disappeared.
Hydra 0.1.1234.abcdef (using nix-1.12pre5413_b4b1f452

https://hydra.nixos.org/build/54580779/download/2/manual

**Comment by ju1m** [comment]
Still broken ='(
As a workaround one can install the disnix and disnixos packages and lookup the manuals locally:
`find /nix -path '*/doc/disnix'`

**Comment by svanderburg** [comment]
Should be solved now thanks to this Hydra change: https://github.com/NixOS/hydra/commit/7857f8325152daba97ef3764133ebc8b58e9860a
