### ISSUE TITLE
How to cleanly delete a deployment?

### ISSUE THREAD

**Issue by LightAndLight** [svanderburg/disnix#11]
Is there a command that sends a deactivate message to all services and deletes the coordinator profile?

I've been playing around with Disnixos and NixOps. `nixops destroy` and `nixops delete` remove the NixOps deployment, but the services that I deployed with Disnixos do not run their deactivation scripts, and I have to manually delete the Disnix manifest to get back to a completely clean slate.

**Comment by svanderburg** [comment]
You can get rid of the deployment state by removing the corresponding Nix coordinator profiles. You can find them in: `/nix/var/nix/profiles/$(whoami)/disnix-coordinator`

So running:

```bash
rm /nix/var/nix/profiles/$(whoami)/disnix-coordinator/*
```

should suffice.

**Comment by svanderburg** [comment]
Perhaps it is be better to have a command allowing you to manage these profiles in more convenient manner, but currently there is none :)

**Comment by LightAndLight** [comment]
Thanks for the response Sander. Your first comment is what I've been doing. If I have the time or inclination I'll look into making it easier :)

**Comment by svanderburg** [comment]
I just extended the `disnix-env` tool in revision with a collection of additional options in revision 3ebfcee8326938e775dd63eed8075de0717dcd84

What you're probably looking for is the `disnix-env --delete-all-generations` command.

**Comment by svanderburg** [comment]
Closing, since I believe these new features address this earlier mentioned shortcoming.
