### ISSUE TITLE
Failure when $TMPDIR does not exist on remote

### ISSUE THREAD

**Issue by rimmington** [svanderburg/disnix#6]
With a local `$TMPDIR` set (by `nix-shell`) to `/run/user/1000` and no corresponding directory on the (Debian) remote, `disnix-env` fails:

```
mktemp: failed to create file via template ‘/run/user/1000/tmp.XXXXXXXXXX’: No such file or directory
Cannot transfer intra-dependency closure!
```

Worked around by setting `TMPDIR=/tmp` when invoking `disnix-env`.

Using Disnix 0.5.

**Comment by svanderburg** [comment]
In the development version I made a change (revision d2290946d636cb620e7dbd62ee7a9872b7a9652b to be precise) that now creates the temp dir if it does not exists
