### ISSUE TITLE
Disnix Docbook link in README is dead

### ISSUE THREAD

**Issue by matthiasbeyer** [svanderburg/disnix#9]
> Disnix has a nice Docbook manual that can be compiled yourself. However, it is also available online.

The link is dead. :disappointed:

**Comment by matthiasbeyer** [comment]
Same for the Disnixos repo, btw.

**Comment by grahamc** [comment]
Similarly, the links to hydra downloads on https://nixos.org/disnix/docs.html is dead.

**Comment by svanderburg** [comment]
Works again thanks to think Hydra change: https://github.com/NixOS/hydra/commit/7857f8325152daba97ef3764133ebc8b58e9860a
